import Theme from 'vitepress-daisyui-theme'
import type { Theme as ThemeType, EnhanceAppContext } from 'vitepress'
import Landing from './Landing.vue'
import Example from './Example.vue'
import './custom.css'

/**
 * chartjs2img uses the stock vitepress-daisyui-theme. Two globals are
 * registered:
 *   <Landing />           — the full-page landing section mounted by
 *                           /en/ and /ja/ index.md.
 *   <Example name="…" />  — Preview / JSON / CLI / HTTP tabbed widget
 *                           backed by docs/public/examples/<slug>.{png,json},
 *                           generated by `bun run docs:examples`.
 */
export default {
  extends: Theme,
  setup() {
    Theme.setup?.()
  },
  enhanceApp(ctx: EnhanceAppContext) {
    Theme.enhanceApp?.(ctx)
    ctx.app.component('Landing', Landing)
    ctx.app.component('Example', Example)
  },
} satisfies ThemeType
