<script setup lang="ts">
/**
 * Landing page for /en/ and /ja/ — modeled on gridgram's Landing.vue
 * but stripped to the sections that apply to chartjs2img:
 *
 *   1. Hero            — title + tagline + CTAs
 *   2. Carousel        — gallery PNG marquee
 *   3. Features        — four cards, one sentence each
 *   4. AI-ready        — four agent-integration channels
 *   5. Final CTA       — repeat of hero CTAs at page end
 *   6. Acknowledgments — upstream open-source projects
 *
 * All user-facing strings come from the page's `landing:` frontmatter
 * so the template stays locale-agnostic.
 */
import { computed } from 'vue'
import { useData } from 'vitepress'

interface CtaLink {
  text: string
  link: string
}
interface FeatureItem {
  title: string
  body: string
}
interface AiReadyItem {
  title: string
  body: string
  link: string
  linkText?: string
}
interface AiReadyContent {
  eyebrow?: string
  title: string
  intro?: string
  items: AiReadyItem[]
}
interface AcknowledgmentsContent {
  title: string
  intro?: string
}
interface LandingFrontmatter {
  hero: {
    name: string
    text: string
    primary?: CtaLink
    ai?: CtaLink
    secondary?: CtaLink
  }
  features?: { items: FeatureItem[] }
  aiReady?: AiReadyContent
  finalCta?: {
    title: string
    text?: string
    primary?: CtaLink
    ai?: CtaLink
    secondary?: CtaLink
  }
  acknowledgments?: AcknowledgmentsContent
}

const { frontmatter } = useData()
const content = computed<LandingFrontmatter>(() => (frontmatter.value as any).landing ?? {})

/** Gallery PNGs (generated by `bun run docs:examples`) used for the
 *  hero marquee. A representative subset of the 18 built-in examples. */
const carouselExamples = [
  '01-bar-chart',
  '03-line-chart',
  '05-pie-chart',
  '07-radar-chart',
  '10-bubble-chart',
  '11-mixed-chart-bar-line',
  '13-bar-with-data-labels',
  '14-line-with-annotation',
  '15-treemap-chart',
  '18-japanese-labels',
]
/** Duplicated so the marquee can translate by -50% for a seamless loop. */
const carouselTrack = [...carouselExamples, ...carouselExamples]

// ----- Acknowledgments (objective data; titles come from frontmatter) ---
interface Acknowledgment {
  name: string
  href: string
  license: string
  role: string
  role_ja: string
}
const acknowledgments: Acknowledgment[] = [
  {
    name: 'Chart.js',
    href: 'https://www.chartjs.org/',
    license: 'MIT',
    role: 'The chart rendering engine this service wraps',
    role_ja: 'このサービスがラップするチャート描画エンジン',
  },
  {
    name: 'puppeteer-core',
    href: 'https://pptr.dev/',
    license: 'Apache-2.0',
    role: 'Headless Chromium control from Node',
    role_ja: 'Node からのヘッドレス Chromium 制御',
  },
  {
    name: 'Chrome for Testing',
    href: 'https://googlechromelabs.github.io/chrome-for-testing/',
    license: 'BSD-3-Clause',
    role: 'Bundled Chromium auto-downloaded at first run',
    role_ja: '初回実行時に自動 DL されるバンドル Chromium',
  },
  {
    name: 'Bun',
    href: 'https://bun.sh/',
    license: 'MIT',
    role: 'Runtime + single-binary compile target',
    role_ja: 'ランタイム + 単一バイナリコンパイル',
  },
  {
    name: 'Noto Sans CJK',
    href: 'https://fonts.google.com/noto',
    license: 'OFL-1.1',
    role: 'Japanese / Chinese / Korean glyph fallback in Docker',
    role_ja: 'Docker での 日/中/韓 グリフフォールバック',
  },
  {
    name: 'VitePress',
    href: 'https://vitepress.dev/',
    license: 'MIT',
    role: 'This documentation site',
    role_ja: 'このドキュメントサイト',
  },
  {
    name: 'vitepress-daisyui-theme',
    href: 'https://github.com/ideamans/vitepress-daisyui-theme',
    license: 'MIT',
    role: 'VitePress theme using DaisyUI',
    role_ja: 'DaisyUI ベースの VitePress テーマ',
  },
]

const siteLang = computed<string>(() => {
  const l = (frontmatter.value as any).lang ?? 'en'
  return String(l).toLowerCase().startsWith('ja') ? 'ja' : 'en'
})
</script>

<template>
  <div class="c2i-landing">
    <!-- ============================ Hero ============================ -->
    <section class="py-20 md:py-28 px-6 text-center">
      <h1 class="text-5xl md:text-6xl font-extrabold tracking-tight leading-none">
        {{ content.hero.name }}
      </h1>
      <p class="text-xl md:text-2xl mt-6 opacity-75 max-w-2xl mx-auto">
        {{ content.hero.text }}
      </p>
      <div class="flex flex-wrap gap-3 justify-center mt-10">
        <a
          v-if="content.hero.primary"
          :href="content.hero.primary.link"
          class="btn btn-primary btn-lg"
        >{{ content.hero.primary.text }}</a>
        <a
          v-if="content.hero.ai"
          :href="content.hero.ai.link"
          class="btn btn-outline btn-primary btn-lg"
        >{{ content.hero.ai.text }}</a>
        <a
          v-if="content.hero.secondary"
          :href="content.hero.secondary.link"
          class="btn btn-ghost btn-lg"
        >{{ content.hero.secondary.text }}</a>
      </div>
    </section>

    <!-- ========================== Carousel ========================== -->
    <section class="c2i-carousel py-10 bg-base-200 overflow-hidden">
      <div class="c2i-carousel__track">
        <a
          v-for="(name, i) in carouselTrack"
          :key="i"
          :href="siteLang === 'ja' ? '/ja/gallery/' : '/en/gallery/'"
          class="c2i-carousel__item"
          tabindex="-1"
        >
          <img :src="`/examples/${name}.png`" :alt="name" loading="lazy" />
        </a>
      </div>
    </section>

    <!-- ========================== Features ========================== -->
    <section v-if="content.features?.items?.length" class="py-20 md:py-24 px-6">
      <div class="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 md:gap-10">
        <div
          v-for="(f, i) in content.features.items"
          :key="i"
          class="flex flex-col items-start"
        >
          <h3 class="font-semibold text-base md:text-lg">{{ f.title }}</h3>
          <p class="text-sm opacity-70 leading-relaxed mt-1.5">
            {{ f.body }}
          </p>
        </div>
      </div>
    </section>

    <!-- ========================== AI-ready ========================== -->
    <section v-if="content.aiReady" class="c2i-ai py-16 md:py-20 px-6 bg-base-200">
      <div class="max-w-6xl mx-auto">
        <header class="text-center mb-10">
          <div v-if="content.aiReady.eyebrow" class="c2i-ai__eyebrow">
            {{ content.aiReady.eyebrow }}
          </div>
          <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.aiReady.title }}
          </h2>
          <p
            v-if="content.aiReady.intro"
            class="opacity-70 mt-3 max-w-2xl mx-auto"
          >{{ content.aiReady.intro }}</p>
        </header>
        <ul class="c2i-ai__grid grid gap-4 md:gap-5 sm:grid-cols-2 lg:grid-cols-4">
          <li v-for="(item, i) in content.aiReady.items" :key="i" class="c2i-ai__card">
            <a :href="item.link" class="c2i-ai__link">
              <h3 class="c2i-ai__title">{{ item.title }}</h3>
              <p class="c2i-ai__body">{{ item.body }}</p>
              <span class="c2i-ai__cta">{{ item.linkText || '→' }}</span>
            </a>
          </li>
        </ul>
      </div>
    </section>

    <!-- ========================== Final CTA ========================== -->
    <section v-if="content.finalCta" class="py-20 md:py-24 px-6 text-center">
      <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
        {{ content.finalCta.title }}
      </h2>
      <p
        v-if="content.finalCta.text"
        class="opacity-70 mt-3 max-w-xl mx-auto"
      >{{ content.finalCta.text }}</p>
      <div class="flex flex-wrap gap-3 justify-center mt-8">
        <a
          v-if="content.finalCta.primary"
          :href="content.finalCta.primary.link"
          class="btn btn-primary btn-lg"
        >{{ content.finalCta.primary.text }}</a>
        <a
          v-if="content.finalCta.ai"
          :href="content.finalCta.ai.link"
          class="btn btn-outline btn-primary btn-lg"
        >{{ content.finalCta.ai.text }}</a>
        <a
          v-if="content.finalCta.secondary"
          :href="content.finalCta.secondary.link"
          class="btn btn-ghost btn-lg"
        >{{ content.finalCta.secondary.text }}</a>
      </div>
    </section>

    <!-- ========================== Acknowledgments ========================== -->
    <section v-if="content.acknowledgments" class="py-16 md:py-20 px-6 bg-base-200">
      <div class="max-w-5xl mx-auto">
        <header class="text-center mb-10">
          <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.acknowledgments.title }}
          </h2>
          <p
            v-if="content.acknowledgments.intro"
            class="opacity-70 mt-3 max-w-2xl mx-auto"
          >{{ content.acknowledgments.intro }}</p>
        </header>
        <ul class="c2i-ack grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          <li v-for="(a, i) in acknowledgments" :key="i" class="c2i-ack__card">
            <a :href="a.href" target="_blank" rel="noopener" class="c2i-ack__name">
              {{ a.name }} ↗
            </a>
            <span class="c2i-ack__license">{{ a.license }}</span>
            <p class="c2i-ack__role">
              {{ siteLang === 'ja' ? a.role_ja : a.role }}
            </p>
          </li>
        </ul>
      </div>
    </section>
  </div>
</template>

<style scoped>
.c2i-landing {
  width: 100%;
}

/* Carousel — full-width marquee with two-copy track for a seamless loop. */
.c2i-carousel {
  position: relative;
}
.c2i-carousel::before,
.c2i-carousel::after {
  content: '';
  position: absolute;
  top: 0;
  bottom: 0;
  width: 72px;
  pointer-events: none;
  z-index: 1;
}
.c2i-carousel::before {
  left: 0;
  background: linear-gradient(to right, var(--fallback-b2, oklch(var(--b2))) 0%, transparent 100%);
}
.c2i-carousel::after {
  right: 0;
  background: linear-gradient(to left, var(--fallback-b2, oklch(var(--b2))) 0%, transparent 100%);
}
.c2i-carousel__track {
  display: flex;
  align-items: center;
  gap: 32px;
  width: max-content;
  animation: c2i-marquee 60s linear infinite;
}
.c2i-carousel:hover .c2i-carousel__track {
  animation-play-state: paused;
}
.c2i-carousel__item {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  padding: 16px 20px;
  background: var(--vp-c-bg, #fff);
  border-radius: 14px;
  border: 1px solid var(--vp-c-divider);
  transition: transform 0.3s;
}
.c2i-carousel__item:hover {
  transform: translateY(-3px);
}
.c2i-carousel__item img {
  height: 220px;
  width: auto;
  max-width: 340px;
  display: block;
  object-fit: contain;
}
@media (max-width: 768px) {
  .c2i-carousel__item img {
    height: 160px;
    max-width: 260px;
  }
}
@keyframes c2i-marquee {
  from {
    transform: translateX(0);
  }
  to {
    transform: translateX(-50%);
  }
}
@media (prefers-reduced-motion: reduce) {
  .c2i-carousel__track {
    animation: none;
  }
}

/* AI-ready */
.c2i-ai__eyebrow {
  display: inline-block;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--vp-c-brand-1);
  padding: 4px 12px;
  border-radius: 999px;
  background: color-mix(in oklab, var(--vp-c-brand-1) 12%, transparent);
  margin-bottom: 14px;
}
.c2i-ai__grid {
  list-style: none;
  padding: 0;
  margin: 0;
}
.c2i-ai__card {
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 14px;
  transition: transform 0.2s, border-color 0.2s, box-shadow 0.2s;
}
.c2i-ai__card:hover {
  transform: translateY(-3px);
  border-color: var(--vp-c-brand-1);
  box-shadow: 0 6px 20px -8px color-mix(in oklab, var(--vp-c-brand-1) 40%, transparent);
}
.c2i-ai__link {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 22px 22px 20px;
  height: 100%;
  text-decoration: none;
  color: inherit;
}
.c2i-ai__title {
  font-weight: 600;
  font-size: 16px;
  margin: 0;
}
.c2i-ai__body {
  font-size: 13.5px;
  opacity: 0.72;
  line-height: 1.55;
  margin: 0;
  flex: 1;
}
.c2i-ai__cta {
  font-size: 13px;
  font-weight: 600;
  color: var(--vp-c-brand-1);
  margin-top: 4px;
}

/* Acknowledgments */
.c2i-ack {
  list-style: none;
  padding: 0;
  margin: 0;
}
.c2i-ack__card {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 14px 16px;
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 10px;
}
.c2i-ack__name {
  font-weight: 600;
  color: var(--vp-c-brand-1);
  text-decoration: none;
}
.c2i-ack__name:hover {
  text-decoration: underline;
}
.c2i-ack__license {
  display: inline-block;
  align-self: flex-start;
  font-size: 11px;
  font-family: var(--vp-font-family-mono, ui-monospace, monospace);
  padding: 1px 6px;
  border-radius: 999px;
  background: var(--vp-c-default-soft, rgba(128, 128, 128, 0.1));
  color: var(--vp-c-text-2);
  margin-top: 2px;
}
.c2i-ack__role {
  font-size: 13px;
  opacity: 0.75;
  line-height: 1.5;
  margin: 2px 0 0;
}
</style>
