<script setup lang="ts">
/**
 * Landing page for /en/ and /ja/ — modeled on gridgram's Landing.vue
 * but stripped to the sections that apply to chartjs2img:
 *
 *   1. Hero            — title + tagline + CTAs
 *   2. Carousel        — gallery PNG marquee
 *   3. Features        — four cards, one sentence each
 *   4. AI-ready        — four agent-integration channels
 *   5. Final CTA       — repeat of hero CTAs at page end
 *   6. Acknowledgments — upstream open-source projects
 *
 * All user-facing strings come from the page's `landing:` frontmatter
 * so the template stays locale-agnostic.
 */
import { computed, ref, watchEffect } from 'vue'
import { useData } from 'vitepress'
import { createHighlighter, type Highlighter } from 'shiki'

interface CtaLink {
  text: string
  link: string
}
interface FeatureItem {
  title: string
  body: string
}
interface AiReadyItem {
  title: string
  body: string
  link: string
  linkText?: string
}
interface AiReadyContent {
  eyebrow?: string
  title: string
  intro?: string
  items: AiReadyItem[]
}
interface AcknowledgmentsContent {
  title: string
  intro?: string
}
interface ConceptSectionContent {
  title?: string
  intro?: string
  /** Path to the SVG under docs/public/ (e.g. '/diagrams/landing-two-flows.svg'). */
  image: string
  alt?: string
}
interface ExampleSectionContent {
  title?: string
  intro?: string
  /** Slug matching docs/public/examples/<slug>.{png,json}. */
  name: string
  sourceLabel?: string
  previewLabel?: string
}
interface ShowcaseSectionContent {
  eyebrow?: string
  title?: string
  intro?: string
  items: Array<{ name: string; title?: string; body?: string }>
}
interface LandingFrontmatter {
  hero: {
    name: string
    text: string
    primary?: CtaLink
    ai?: CtaLink
    secondary?: CtaLink
  }
  features?: { items: FeatureItem[] }
  concept?: ConceptSectionContent
  example?: ExampleSectionContent
  showcase?: ShowcaseSectionContent
  aiReady?: AiReadyContent
  finalCta?: {
    title: string
    text?: string
    primary?: CtaLink
    ai?: CtaLink
    secondary?: CtaLink
  }
  acknowledgments?: AcknowledgmentsContent
}

const { frontmatter } = useData()
const content = computed<LandingFrontmatter>(() => (frontmatter.value as any).landing ?? {})

/** Escape a string for safe interpolation into a v-html template. Only
 *  needed for the two characters that can break out of text context — the
 *  rest passes through verbatim. */
function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/** Hero title with the digit "2" lifted into an accent-coloured span so
 *  the mark's red bar echoes in the wordmark. Applies to any hero name
 *  that contains a "2" (both EN and JA use `chartjs2img`). */
const heroNameHtml = computed<string>(() => {
  const name = content.value.hero?.name ?? ''
  return escHtml(name).replace(/2/g, '<span class="c2i-hero__accent">2</span>')
})

/** Gallery PNGs (generated by `bun run docs:examples`) used for the
 *  hero marquee. A representative subset of the 18 built-in examples. */
const carouselExamples = [
  '01-bar-chart',
  '03-line-chart',
  '05-pie-chart',
  '07-radar-chart',
  '10-bubble-chart',
  '11-mixed-chart-bar-line',
  '13-bar-with-data-labels',
  '14-line-with-annotation',
  '15-treemap-chart',
  '18-japanese-labels',
]
/** Duplicated so the marquee can translate by -50% for a seamless loop. */
const carouselTrack = [...carouselExamples, ...carouselExamples]

// ----- Acknowledgments (objective data; titles come from frontmatter) ---
interface Acknowledgment {
  name: string
  href: string
  license: string
  role: string
  role_ja: string
}
const acknowledgments: Acknowledgment[] = [
  {
    name: 'Chart.js',
    href: 'https://www.chartjs.org/',
    license: 'MIT',
    role: 'The chart rendering engine this service wraps',
    role_ja: 'このサービスがラップするチャート描画エンジン',
  },
  {
    name: 'puppeteer-core',
    href: 'https://pptr.dev/',
    license: 'Apache-2.0',
    role: 'Headless Chromium control from Node',
    role_ja: 'Node からのヘッドレス Chromium 制御',
  },
  {
    name: 'Chrome for Testing',
    href: 'https://googlechromelabs.github.io/chrome-for-testing/',
    license: 'BSD-3-Clause',
    role: 'Bundled Chromium auto-downloaded at first run',
    role_ja: '初回実行時に自動 DL されるバンドル Chromium',
  },
  {
    name: 'Bun',
    href: 'https://bun.sh/',
    license: 'MIT',
    role: 'Runtime + single-binary compile target',
    role_ja: 'ランタイム + 単一バイナリコンパイル',
  },
  {
    name: 'Noto Sans CJK',
    href: 'https://fonts.google.com/noto',
    license: 'OFL-1.1',
    role: 'Japanese / Chinese / Korean glyph fallback in Docker',
    role_ja: 'Docker での 日/中/韓 グリフフォールバック',
  },
  {
    name: 'VitePress',
    href: 'https://vitepress.dev/',
    license: 'MIT',
    role: 'This documentation site',
    role_ja: 'このドキュメントサイト',
  },
  {
    name: 'vitepress-daisyui-theme',
    href: 'https://github.com/ideamans/vitepress-daisyui-theme',
    license: 'MIT',
    role: 'VitePress theme using DaisyUI',
    role_ja: 'DaisyUI ベースの VitePress テーマ',
  },
]

const siteLang = computed<string>(() => {
  const l = (frontmatter.value as any).lang ?? 'en'
  return String(l).toLowerCase().startsWith('ja') ? 'ja' : 'en'
})

// ----- Live example: fetch the JSON that produced the preview PNG, so the
//       left-hand side of the split stays in sync with src/examples.ts.
//       Shiki highlights the JSON so it reads like a normal fenced code block
//       (matches the rest of the docs' ``` syntax styling). -----
const exampleJson = ref<string>('')
const exampleJsonHtml = ref<string>('')

let highlighterPromise: Promise<Highlighter> | null = null
function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({
      langs: ['json'],
      themes: ['github-light', 'github-dark'],
    })
  }
  return highlighterPromise
}

watchEffect(async () => {
  const slug = content.value.example?.name
  if (!slug || typeof fetch === 'undefined') return
  try {
    const r = await fetch(`/examples/${slug}.json`)
    if (!r.ok) return
    const raw = await r.text()
    const pretty = (() => {
      try {
        return JSON.stringify(JSON.parse(raw), null, 2)
      } catch {
        return raw
      }
    })()
    exampleJson.value = pretty
    try {
      const hl = await getHighlighter()
      const html = hl.codeToHtml(pretty.replace(/\s+$/, ''), {
        lang: 'json',
        themes: { light: 'github-light', dark: 'github-dark' },
        defaultColor: false,
      })
      // Mirror VitePress's markdown ```json fence styling: wrap with
      // `language-json` + `vp-doc` bits so our custom-css rules (and
      // the theme's own ones) can pick the same colors + bg.
      exampleJsonHtml.value = html.replace(/<pre class="shiki/, '<pre class="shiki vp-code')
    } catch {
      /* non-fatal — fall back to plain <pre> in the template */
    }
  } catch {
    /* ignore — the section simply shows a loading state */
  }
})
</script>

<template>
  <div class="c2i-landing">
    <!-- ============================ Hero ============================ -->
    <section class="py-20 md:py-28 px-6 text-center">
      <img
        src="/logo.svg"
        alt=""
        width="96"
        height="96"
        class="c2i-hero__logo"
      />
      <h1
        class="text-5xl md:text-6xl font-extrabold tracking-tight leading-none"
        v-html="heroNameHtml"
      ></h1>
      <p class="text-xl md:text-2xl mt-6 opacity-75 max-w-2xl mx-auto">
        {{ content.hero.text }}
      </p>
      <div class="flex flex-wrap gap-3 justify-center mt-10">
        <a
          v-if="content.hero.primary"
          :href="content.hero.primary.link"
          class="btn btn-primary btn-lg"
        >{{ content.hero.primary.text }}</a>
        <a
          v-if="content.hero.ai"
          :href="content.hero.ai.link"
          class="btn btn-outline btn-primary btn-lg"
        >{{ content.hero.ai.text }}</a>
        <a
          v-if="content.hero.secondary"
          :href="content.hero.secondary.link"
          class="btn btn-ghost btn-lg"
        >{{ content.hero.secondary.text }}</a>
      </div>
    </section>

    <!-- ========================== Carousel ========================== -->
    <section class="c2i-carousel py-10 bg-base-200 overflow-hidden">
      <div class="c2i-carousel__track">
        <a
          v-for="(name, i) in carouselTrack"
          :key="i"
          :href="siteLang === 'ja' ? '/ja/gallery/' : '/en/gallery/'"
          class="c2i-carousel__item"
          tabindex="-1"
        >
          <img :src="`/examples/${name}.png`" :alt="name" loading="lazy" />
        </a>
      </div>
    </section>

    <!-- ========================== Concept ========================== -->
    <section v-if="content.concept" class="c2i-concept py-16 md:py-20 px-6">
      <div class="max-w-6xl mx-auto text-center">
        <h2 v-if="content.concept.title" class="text-3xl md:text-4xl font-bold tracking-tight">
          {{ content.concept.title }}
        </h2>
        <p
          v-if="content.concept.intro"
          class="opacity-70 mt-3 max-w-2xl mx-auto"
        >{{ content.concept.intro }}</p>
        <figure class="c2i-concept__figure">
          <img
            :src="content.concept.image"
            :alt="content.concept.alt || 'Concept diagram'"
            class="c2i-concept__img"
          />
        </figure>
      </div>
    </section>

    <!-- ========================== Features ========================== -->
    <section v-if="content.features?.items?.length" class="py-20 md:py-24 px-6 bg-base-200">
      <div class="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 md:gap-10">
        <div
          v-for="(f, i) in content.features.items"
          :key="i"
          class="flex flex-col items-start"
        >
          <h3 class="font-semibold text-base md:text-lg">{{ f.title }}</h3>
          <p class="text-sm opacity-70 leading-relaxed mt-1.5">
            {{ f.body }}
          </p>
        </div>
      </div>
    </section>

    <!-- ======================= Live example ======================== -->
    <section v-if="content.example" class="c2i-ex py-20 md:py-24 px-6">
      <div class="max-w-6xl mx-auto">
        <header v-if="content.example.title || content.example.intro" class="text-center mb-10">
          <h2 v-if="content.example.title" class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.example.title }}
          </h2>
          <p v-if="content.example.intro" class="opacity-70 mt-3 max-w-2xl mx-auto">
            {{ content.example.intro }}
          </p>
        </header>
        <div class="c2i-ex__split">
          <figure class="c2i-ex__figure">
            <figcaption class="c2i-ex__caption">{{ content.example.sourceLabel || 'Source JSON' }}</figcaption>
            <div
              v-if="exampleJsonHtml"
              class="language-json c2i-ex__shiki"
              v-html="exampleJsonHtml"
            />
            <pre v-else class="c2i-ex__code"><code>{{ exampleJson || '…' }}</code></pre>
          </figure>
          <figure class="c2i-ex__figure">
            <figcaption class="c2i-ex__caption">{{ content.example.previewLabel || 'Rendered PNG' }}</figcaption>
            <div class="c2i-ex__image">
              <img :src="`/examples/${content.example.name}.png`" :alt="content.example.name" />
            </div>
          </figure>
        </div>
      </div>
    </section>

    <!-- ========================= Showcase ========================== -->
    <section v-if="content.showcase" class="c2i-show py-16 md:py-20 px-6 bg-base-200">
      <div class="max-w-6xl mx-auto">
        <header class="text-center mb-10">
          <div v-if="content.showcase.eyebrow" class="c2i-ai__eyebrow">{{ content.showcase.eyebrow }}</div>
          <h2 v-if="content.showcase.title" class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.showcase.title }}
          </h2>
          <p v-if="content.showcase.intro" class="opacity-70 mt-3 max-w-2xl mx-auto">
            {{ content.showcase.intro }}
          </p>
        </header>
        <div class="c2i-show__grid">
          <figure v-for="(item, i) in content.showcase.items" :key="i" class="c2i-show__card">
            <div class="c2i-show__image">
              <img :src="`/examples/${item.name}.png`" :alt="item.name" />
            </div>
            <figcaption v-if="item.title || item.body" class="c2i-show__caption">
              <h3 v-if="item.title" class="c2i-show__title">{{ item.title }}</h3>
              <p v-if="item.body" class="c2i-show__body">{{ item.body }}</p>
            </figcaption>
          </figure>
        </div>
      </div>
    </section>

    <!-- ========================== AI-ready ========================== -->
    <section v-if="content.aiReady" class="c2i-ai py-16 md:py-20 px-6">
      <div class="max-w-6xl mx-auto">
        <header class="text-center mb-10">
          <div v-if="content.aiReady.eyebrow" class="c2i-ai__eyebrow">
            {{ content.aiReady.eyebrow }}
          </div>
          <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.aiReady.title }}
          </h2>
          <p
            v-if="content.aiReady.intro"
            class="opacity-70 mt-3 max-w-2xl mx-auto"
          >{{ content.aiReady.intro }}</p>
        </header>
        <ul class="c2i-ai__grid grid gap-4 md:gap-5 sm:grid-cols-2 lg:grid-cols-4">
          <li v-for="(item, i) in content.aiReady.items" :key="i" class="c2i-ai__card">
            <a :href="item.link" class="c2i-ai__link">
              <h3 class="c2i-ai__title">{{ item.title }}</h3>
              <p class="c2i-ai__body">{{ item.body }}</p>
              <span class="c2i-ai__cta">{{ item.linkText || '→' }}</span>
            </a>
          </li>
        </ul>
      </div>
    </section>

    <!-- ========================== Final CTA ========================== -->
    <section v-if="content.finalCta" class="py-20 md:py-24 px-6 text-center bg-base-200">
      <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
        {{ content.finalCta.title }}
      </h2>
      <p
        v-if="content.finalCta.text"
        class="opacity-70 mt-3 max-w-xl mx-auto"
      >{{ content.finalCta.text }}</p>
      <div class="flex flex-wrap gap-3 justify-center mt-8">
        <a
          v-if="content.finalCta.primary"
          :href="content.finalCta.primary.link"
          class="btn btn-primary btn-lg"
        >{{ content.finalCta.primary.text }}</a>
        <a
          v-if="content.finalCta.ai"
          :href="content.finalCta.ai.link"
          class="btn btn-outline btn-primary btn-lg"
        >{{ content.finalCta.ai.text }}</a>
        <a
          v-if="content.finalCta.secondary"
          :href="content.finalCta.secondary.link"
          class="btn btn-ghost btn-lg"
        >{{ content.finalCta.secondary.text }}</a>
      </div>
    </section>

    <!-- ========================== Acknowledgments ========================== -->
    <section v-if="content.acknowledgments" class="py-16 md:py-20 px-6">
      <div class="max-w-5xl mx-auto">
        <header class="text-center mb-10">
          <h2 class="text-3xl md:text-4xl font-bold tracking-tight">
            {{ content.acknowledgments.title }}
          </h2>
          <p
            v-if="content.acknowledgments.intro"
            class="opacity-70 mt-3 max-w-2xl mx-auto"
          >{{ content.acknowledgments.intro }}</p>
        </header>
        <ul class="c2i-ack grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          <li v-for="(a, i) in acknowledgments" :key="i" class="c2i-ack__card">
            <a :href="a.href" target="_blank" rel="noopener" class="c2i-ack__name">
              {{ a.name }} ↗
            </a>
            <span class="c2i-ack__license">{{ a.license }}</span>
            <p class="c2i-ack__role">
              {{ siteLang === 'ja' ? a.role_ja : a.role }}
            </p>
          </li>
        </ul>
      </div>
    </section>
  </div>
</template>

<style scoped>
.c2i-landing {
  width: 100%;
}

/* Hero logo — sits above the wordmark, mirroring the brand masthead
   in tmp/brand.html. Kept a bit smaller than the mark in brand.html so
   the title still leads the eye. */
.c2i-hero__logo {
  display: block;
  width: 96px;
  height: 96px;
  margin: 0 auto 20px;
}

/* The "2" in "chartjs2img" picks up the accent red — the same bar that
   leads the mark. `:deep()` because the span is injected via v-html and
   scoped CSS otherwise wouldn't reach it. */
.c2i-landing :deep(.c2i-hero__accent) {
  color: var(--color-accent, #ff6384);
}

/* Carousel — full-width marquee with two-copy track for a seamless loop. */
.c2i-carousel {
  position: relative;
}
.c2i-carousel::before,
.c2i-carousel::after {
  content: '';
  position: absolute;
  top: 0;
  bottom: 0;
  width: 72px;
  pointer-events: none;
  z-index: 1;
}
.c2i-carousel::before {
  left: 0;
  background: linear-gradient(to right, var(--fallback-b2, oklch(var(--b2))) 0%, transparent 100%);
}
.c2i-carousel::after {
  right: 0;
  background: linear-gradient(to left, var(--fallback-b2, oklch(var(--b2))) 0%, transparent 100%);
}
.c2i-carousel__track {
  display: flex;
  align-items: center;
  gap: 32px;
  width: max-content;
  animation: c2i-marquee 60s linear infinite;
}
.c2i-carousel:hover .c2i-carousel__track {
  animation-play-state: paused;
}
.c2i-carousel__item {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  padding: 16px 20px;
  background: var(--vp-c-bg, #fff);
  border-radius: 14px;
  border: 1px solid var(--vp-c-divider);
  transition: transform 0.3s;
}
.c2i-carousel__item:hover {
  transform: translateY(-3px);
}
.c2i-carousel__item img {
  height: 220px;
  width: auto;
  max-width: 340px;
  display: block;
  object-fit: contain;
}
@media (max-width: 768px) {
  .c2i-carousel__item img {
    height: 160px;
    max-width: 260px;
  }
}
@keyframes c2i-marquee {
  from {
    transform: translateX(0);
  }
  to {
    transform: translateX(-50%);
  }
}
@media (prefers-reduced-motion: reduce) {
  .c2i-carousel__track {
    animation: none;
  }
}

/* AI-ready */
.c2i-ai__eyebrow {
  display: inline-block;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--vp-c-brand-1);
  padding: 4px 12px;
  border-radius: 999px;
  background: color-mix(in oklab, var(--vp-c-brand-1) 12%, transparent);
  margin-bottom: 14px;
}
.c2i-ai__grid {
  list-style: none;
  padding: 0;
  margin: 0;
}
.c2i-ai__card {
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 14px;
  transition: transform 0.2s, border-color 0.2s, box-shadow 0.2s;
}
.c2i-ai__card:hover {
  transform: translateY(-3px);
  border-color: var(--vp-c-brand-1);
  box-shadow: 0 6px 20px -8px color-mix(in oklab, var(--vp-c-brand-1) 40%, transparent);
}
.c2i-ai__link {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 22px 22px 20px;
  height: 100%;
  text-decoration: none;
  color: inherit;
}
.c2i-ai__title {
  font-weight: 600;
  font-size: 16px;
  margin: 0;
}
.c2i-ai__body {
  font-size: 13.5px;
  opacity: 0.72;
  line-height: 1.55;
  margin: 0;
  flex: 1;
}
.c2i-ai__cta {
  font-size: 13px;
  font-weight: 600;
  color: var(--vp-c-brand-1);
  margin-top: 4px;
}

/* Concept diagram — centered SVG below the carousel, explains the
   two destinations (interactive web via Chart.js, or PNG via
   chartjs2img for Slack / email). */
.c2i-concept__figure {
  margin: 28px auto 0;
  padding: 20px 24px;
  background: var(--vp-c-bg, #ffffff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 14px;
  /* No hard cap — let the figure fill the (max-w-6xl ≈ 1152px) outer
     container so the wide landing diagram breathes on desktop. The
     inner <img> width:100% keeps the SVG edge-to-edge. */
}
.c2i-concept__img {
  display: block;
  width: 100%;
  height: auto;
}

/* Live example — chart left, JSON right */
.c2i-ex__split {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: 28px;
  align-items: stretch;
}
@media (max-width: 860px) {
  .c2i-ex__split {
    grid-template-columns: 1fr;
  }
}
.c2i-ex__figure {
  margin: 0;
  display: flex;
  flex-direction: column;
  min-width: 0;
}
.c2i-ex__caption {
  font-size: 12px;
  font-family: var(--vp-font-family-mono);
  color: var(--vp-c-text-3);
  padding: 8px 12px;
  background: var(--vp-c-bg-soft);
  border: 1px solid var(--vp-c-divider);
  border-bottom: 0;
  border-radius: 10px 10px 0 0;
}
.c2i-ex__image {
  display: flex;
  align-items: center;
  justify-content: center;
  background: repeating-conic-gradient(#f6f6f6 0% 25%, #ffffff 25% 50%) 0 0 / 20px 20px;
  padding: 20px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 0 0 10px 10px;
  flex: 1;
  min-height: 320px;
}
.c2i-ex__image img {
  max-width: 100%;
  max-height: 460px;
  height: auto;
  display: block;
}
.c2i-ex__code {
  margin: 0;
  padding: 16px 20px;
  background: var(--vp-code-block-bg, var(--vp-c-bg-alt));
  border: 1px solid var(--vp-c-divider);
  border-top: 0;
  border-radius: 0 0 10px 10px;
  font-family: var(--vp-font-family-mono);
  font-size: 12.5px;
  line-height: 1.55;
  color: var(--vp-c-text-1);
  overflow: auto;
  max-height: 460px;
  flex: 1;
}
.c2i-ex__code code {
  white-space: pre;
  font-family: inherit;
}

/* Shiki-highlighted panel. Match the VitePress fenced-block look
   exactly: the outer wrapper carries `--vp-code-block-bg` (same
   variable `.vp-doc div[class*="language-"]` reads), and the inner
   <pre> is made transparent — otherwise Shiki's inline
   `background-color: var(--shiki-light)` on <pre> wins and paints
   the block white instead of the docs' soft gray. */
.c2i-ex__shiki {
  margin: 0 !important;
  border: 1px solid var(--vp-c-divider);
  border-top: 0;
  border-radius: 0 0 10px 10px;
  /* Match vitepress-daisyui-theme's `.prose div[class*="language-"]`
     rule exactly — it uses Shiki's own *-bg fallback (#f6f8fa light,
     #24292e dark), not VitePress's --vp-code-block-bg. Keep the two
     in sync or the landing's code panel diverges from the rest of the
     docs' fenced blocks. */
  background: var(--shiki-light-bg, #f6f8fa);
  overflow: hidden;
  flex: 1;
  display: flex;
}
html.dark .c2i-ex__shiki {
  background: var(--shiki-dark-bg, #24292e);
}
.c2i-ex__shiki :deep(pre.shiki),
.c2i-ex__shiki :deep(pre.vp-code) {
  margin: 0;
  padding: 16px 20px;
  /* Override the inline style Shiki emits on <pre> so the outer
     wrapper's `--vp-code-block-bg` shows through. Same trick VitePress
     uses for its own fenced blocks. */
  background: transparent !important;
  font-size: 12.5px;
  line-height: 1.55;
  overflow: auto;
  max-height: 460px;
  width: 100%;
  border-radius: 0;
}
.c2i-ex__shiki :deep(code) {
  font-family: var(--vp-font-family-mono);
  white-space: pre;
  display: block;
  background: transparent !important;
}
/* Pick the right Shiki color per theme — the `defaultColor: false`
   option above emits both --shiki-light and --shiki-dark on every
   token, and VitePress's own light/dark rules apply to any .vp-code
   inside a `.vp-doc` block. These rules repeat that logic for our
   outer-container case (Landing isn't inside `.vp-doc`). */
.c2i-ex__shiki :deep(.shiki span) {
  color: var(--shiki-light);
}
:root.dark .c2i-ex__shiki :deep(.shiki span) {
  color: var(--shiki-dark);
}

/* Showcase — two complex examples side-by-side */
.c2i-show__grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 24px;
}
@media (max-width: 860px) {
  .c2i-show__grid {
    grid-template-columns: 1fr;
  }
}
.c2i-show__card {
  margin: 0;
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 14px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s;
}
.c2i-show__card:hover {
  transform: translateY(-3px);
  border-color: var(--vp-c-brand-1);
  box-shadow: 0 8px 24px -12px color-mix(in oklab, var(--vp-c-brand-1) 40%, transparent);
}
.c2i-show__image {
  padding: 18px;
  background: #ffffff;
}
.c2i-show__image img {
  width: 100%;
  height: auto;
  display: block;
}
.c2i-show__caption {
  padding: 16px 20px 20px;
  border-top: 1px solid var(--vp-c-divider);
}
.c2i-show__title {
  margin: 0 0 6px;
  font-size: 15px;
  font-weight: 600;
}
.c2i-show__body {
  margin: 0;
  font-size: 13px;
  line-height: 1.55;
  color: var(--vp-c-text-2);
}

/* Acknowledgments */
.c2i-ack {
  list-style: none;
  padding: 0;
  margin: 0;
}
.c2i-ack__card {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 14px 16px;
  background: var(--vp-c-bg, #fff);
  border: 1px solid var(--vp-c-divider);
  border-radius: 10px;
}
.c2i-ack__name {
  font-weight: 600;
  color: var(--vp-c-brand-1);
  text-decoration: none;
}
.c2i-ack__name:hover {
  text-decoration: underline;
}
.c2i-ack__license {
  display: inline-block;
  align-self: flex-start;
  font-size: 11px;
  font-family: var(--vp-font-family-mono, ui-monospace, monospace);
  padding: 1px 6px;
  border-radius: 999px;
  background: var(--vp-c-default-soft, rgba(128, 128, 128, 0.1));
  color: var(--vp-c-text-2);
  margin-top: 2px;
}
.c2i-ack__role {
  font-size: 13px;
  opacity: 0.75;
  line-height: 1.5;
  margin: 2px 0 0;
}
</style>
